/**
 * Image universal generator catalog — kept separate from the node component so
 * App / MegaMenu can import metadata without pulling the full node into the main chunk.
 */
export const IMAGE_UNIVERSAL_MODEL_DEFS = {
  Auto: {
    name: 'Auto',
    provider: 'System',
    featured: false,
    tags: [] as string[],
    description: 'Automatically select the best model',
    type: 'generation',
  },
  'Nano Banana 2': {
    name: 'Nano Banana 2',
    provider: 'Freepik',
    featured: true,
    tags: ['New', '80', '15s'],
    description: 'State-of-the-art image generation model',
    type: 'generation',
  },
  'Nano Banana 2 Pro': {
    name: 'Nano Banana 2 Pro',
    provider: 'Freepik',
    featured: true,
    tags: ['Pro', 'JSON', 'High Fidelity'],
    description: 'Advanced image generation with JSON control',
    type: 'generation',
  },
  recraftv4: {
    name: 'Recraft V4',
    provider: 'Recraft',
    featured: true,
    tags: ['Vector', 'Fast'],
    description: 'Professional vector and raster generation',
    type: 'generation',
  },
  recraftv3: {
    name: 'Recraft V3',
    provider: 'Recraft',
    featured: false,
    tags: ['Classic'],
    description: 'Reliable image generation',
    type: 'generation',
  },
  kora: {
    name: 'Kora Reality',
    provider: 'Kora',
    featured: false,
    tags: ['Artistic'],
    description: 'Artistic style generation',
    type: 'generation',
  },
  flux: {
    name: 'Flux',
    provider: 'Black Forest Labs',
    featured: true,
    tags: ['Pro', '4K'],
    description: 'High-fidelity image generation',
    type: 'generation',
  },
  'remove-bg': {
    name: 'Remove Background',
    provider: 'Editing',
    featured: false,
    tags: ['Instant'],
    description: 'Remove image background automatically',
    type: 'editing',
  },
  'creative-upscale': {
    name: 'Creative Upscale',
    provider: 'Editing',
    featured: false,
    tags: ['2-16x'],
    description: 'Upscale with creative enhancement',
    type: 'editing',
  },
  'precision-upscale': {
    name: 'Precision Upscale',
    provider: 'Editing',
    featured: false,
    tags: ['Sharp'],
    description: 'Precise upscaling with detail preservation',
    type: 'editing',
  },
  relight: {
    name: 'Relight',
    provider: 'Editing',
    featured: true,
    tags: ['Studio'],
    description: 'Change lighting and atmosphere',
    type: 'editing',
  },
  'skin-enhancer': {
    name: 'Skin Enhancer',
    provider: 'Editing',
    featured: false,
    tags: ['Portrait'],
    description: 'Professional skin retouching',
    type: 'editing',
  },
  'change-camera': {
    name: 'Change Camera',
    provider: 'Editing',
    featured: false,
    tags: ['3D'],
    description: 'Adjust camera angle and perspective',
    type: 'editing',
  },
  'flux-expand': {
    name: 'Flux Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Flux',
    type: 'editing',
  },
  'seedream-expand': {
    name: 'Seedream Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Seedream',
    type: 'editing',
  },
  'ideogram-expand': {
    name: 'Ideogram Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Ideogram',
    type: 'editing',
  },
  'style-transfer': {
    name: 'Style Transfer',
    provider: 'Editing',
    featured: true,
    tags: ['Artistic'],
    description: 'Transfer style from reference image',
    type: 'editing',
  },
  'quiver-text-to-vector': {
    name: 'Text to Vector',
    provider: 'Quiver',
    featured: false,
    tags: ['SVG', 'Vector'],
    description: 'Generate SVG vectors from text prompts',
    type: 'generation',
  },
  'quiver-image-to-vector': {
    name: 'Image to Vector',
    provider: 'Quiver',
    featured: false,
    tags: ['SVG', 'Vectorize'],
    description: 'Vectorize raster images to SVG',
    type: 'editing',
  },
} as const;

export type ImageUniversalModelId = keyof typeof IMAGE_UNIVERSAL_MODEL_DEFS;

export const MODELS = Object.keys(IMAGE_UNIVERSAL_MODEL_DEFS) as ImageUniversalModelId[];
