/**
 * Image universal generator catalog — kept separate from the node component so
 * App / MegaMenu can import metadata without pulling the full node into the main chunk.
 */
export const IMAGE_UNIVERSAL_MODEL_DEFS = {
  Auto: {
    name: 'Auto',
    provider: 'System',
    featured: false,
    tags: [] as string[],
    description: 'Automatically select the best model',
    type: 'generation',
  },
  'Nano Banana 2': {
    name: 'Nano Banana 2',
    provider: 'Freepik',
    featured: true,
    tags: ['New', '80', '15s'],
    description: 'State-of-the-art image generation model',
    type: 'generation',
  },
  'Nano Banana 2 Pro': {
    name: 'Nano Banana 2 Pro',
    provider: 'Freepik',
    featured: true,
    tags: ['Pro', 'JSON', 'High Fidelity'],
    description: 'Advanced image generation with JSON control',
    type: 'generation',
  },
  'google-imagegen-4': {
    name: 'Google Imagegen 4',
    provider: 'Google',
    featured: true,
    tags: ['Latest', 'Multimodal'],
    description: 'Google\'s latest image generation model',
    type: 'generation',
  },
  recraftv4: {
    name: 'Recraft V4',
    provider: 'Recraft',
    featured: true,
    tags: ['Vector', 'Fast'],
    description: 'Professional vector and raster generation',
    type: 'generation',
  },
  recraftv3: {
    name: 'Recraft V3',
    provider: 'Recraft',
    featured: false,
    tags: ['Classic'],
    description: 'Reliable image generation',
    type: 'generation',
  },
  'ideogram-v3-turbo': {
    name: 'Ideogram V3 Turbo',
    provider: 'Ideogram',
    featured: true,
    tags: ['Fast', 'Creative'],
    description: 'Fast creative image generation with text support',
    type: 'generation',
  },
  'flux-1-1-pro': {
    name: 'Flux 1.1 Pro',
    provider: 'Black Forest Labs',
    featured: true,
    tags: ['Pro', '4K'],
    description: 'Professional-grade image generation',
    type: 'generation',
  },
  'flux-2-pro': {
    name: 'Flux 2 Pro',
    provider: 'Black Forest Labs',
    featured: true,
    tags: ['Latest', '4K', 'Advanced'],
    description: 'Next-gen professional image generation',
    type: 'generation',
  },
  'flux-context-pro': {
    name: 'Flux Context Pro',
    provider: 'Black Forest Labs',
    featured: false,
    tags: ['Context-aware'],
    description: 'Context-aware image generation',
    type: 'generation',
  },
  'flux-dev': {
    name: 'Flux Dev',
    provider: 'Black Forest Labs',
    featured: false,
    tags: ['Development'],
    description: 'Development version of Flux',
    type: 'generation',
  },
  flux: {
    name: 'Flux',
    provider: 'Black Forest Labs',
    featured: false,
    tags: ['Classic'],
    description: 'High-fidelity image generation',
    type: 'generation',
  },
  'remove-bg': {
    name: 'Remove Background',
    provider: 'Editing',
    featured: false,
    tags: ['Instant'],
    description: 'Remove image background automatically',
    type: 'editing',
  },
  'creative-upscale': {
    name: 'Creative Upscale',
    provider: 'Editing',
    featured: false,
    tags: ['2-16x'],
    description: 'Upscale with creative enhancement',
    type: 'editing',
  },
  'precision-upscale': {
    name: 'Precision Upscale',
    provider: 'Editing',
    featured: false,
    tags: ['Sharp'],
    description: 'Precise upscaling with detail preservation',
    type: 'editing',
  },
  relight: {
    name: 'Relight',
    provider: 'Editing',
    featured: true,
    tags: ['Studio'],
    description: 'Change lighting and atmosphere',
    type: 'editing',
  },
  'skin-enhancer': {
    name: 'Skin Enhancer',
    provider: 'Editing',
    featured: false,
    tags: ['Portrait'],
    description: 'Professional skin retouching',
    type: 'editing',
  },
  'change-camera': {
    name: 'Change Camera',
    provider: 'Editing',
    featured: false,
    tags: ['3D'],
    description: 'Adjust camera angle and perspective',
    type: 'editing',
  },
  'flux-expand': {
    name: 'Flux Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Flux',
    type: 'editing',
  },
  'seedream-expand': {
    name: 'Seedream Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Seedream',
    type: 'editing',
  },
  'ideogram-expand': {
    name: 'Ideogram Expand',
    provider: 'Editing',
    featured: false,
    tags: ['Outpaint'],
    description: 'Expand image with Ideogram',
    type: 'editing',
  },
  'style-transfer': {
    name: 'Style Transfer',
    provider: 'Editing',
    featured: true,
    tags: ['Artistic'],
    description: 'Transfer style from reference image',
    type: 'editing',
  },
  'quiver-text-to-vector': {
    name: 'Text to Vector',
    provider: 'Quiver',
    featured: false,
    tags: ['SVG', 'Vector'],
    description: 'Generate SVG vectors from text prompts',
    type: 'generation',
  },
  'quiver-image-to-vector': {
    name: 'Image to Vector',
    provider: 'Quiver',
    featured: false,
    tags: ['SVG', 'Vectorize'],
    description: 'Vectorize raster images to SVG',
    type: 'editing',
  },
  'gfpgan': {
    name: 'GFPGAN Face Restoration',
    provider: 'Replicate',
    featured: true,
    tags: ['Face', 'Upscale', '2-4x'],
    description: 'Restore and upscale faces in images',
    type: 'editing',
  },
  'codeformer': {
    name: 'CodeFormer Face Restoration',
    provider: 'Replicate',
    featured: true,
    tags: ['Face', 'Restore', 'Old Photos'],
    description: 'Restore faces in old photos or AI-generated images',
    type: 'editing',
  },
  'topaz-upscale': {
    name: 'Topaz Upscale',
    provider: 'Topaz Labs',
    featured: true,
    tags: ['Professional', '2-6x', 'Face'],
    description: 'Professional-grade AI image upscaling with face enhancement',
    type: 'editing',
  },
  'flux-kontext-pro': {
    name: 'Flux Kontext Pro',
    provider: 'Black Forest Labs',
    featured: true,
    tags: ['Edit', 'Style Transfer', 'Text'],
    description: 'State-of-the-art text-based image editing with generation capabilities',
    type: 'editing',
  },
} as const;

export type ImageUniversalModelId = keyof typeof IMAGE_UNIVERSAL_MODEL_DEFS;

export const MODELS = Object.keys(IMAGE_UNIVERSAL_MODEL_DEFS) as ImageUniversalModelId[];
