/**
 * Video universal generator catalog — separate from the node component so
 * App / MegaMenu can import metadata without pulling the full node into the main chunk.
 */
export const VIDEO_UNIVERSAL_MODEL_DEFS = {
  Auto: {
    name: 'Auto',
    provider: 'System',
    featured: false,
    tags: [] as string[],
    supportsImageInput: true,
    supportsEndFrame: true,
  },
  kling3: {
    name: 'Kling 3',
    provider: 'Kling',
    featured: true,
    tags: ['High Quality', '10s'],
    description: 'Advanced video generation with motion control',
    supportsImageInput: true,
    supportsEndFrame: true,
  },
  runway: {
    name: 'Runway Gen-4',
    provider: 'Runway',
    featured: true,
    tags: ['Turbo', '10s'],
    description: 'Fast generation with cinematic quality',
    supportsImageInput: true,
    supportsEndFrame: false,
  },
  minimax: {
    name: 'MiniMax',
    provider: 'MiniMax',
    featured: false,
    tags: ['Live', '6s'],
    description: 'Real-time video generation',
    supportsImageInput: true,
    supportsEndFrame: false,
  },
  'minimax-video-01': {
    name: 'Minimax Video-01',
    provider: 'Minimax',
    featured: true,
    tags: ['720p', '6s', 'Cinematic'],
    description: 'High-quality 720p video generation with cinematic camera movement (Hailuo)',
    supportsImageInput: true,
    supportsEndFrame: false,
  },
  pixverse: {
    name: 'PixVerse V5',
    provider: 'PixVerse',
    featured: false,
    tags: ['Motion', '10s', 'Sound'],
    description: 'Smooth motion and transitions with AI sound generation',
    supportsImageInput: true,
    supportsEndFrame: true,
    supportsSoundGeneration: true,
  },
  seedance: {
    name: 'Seedance',
    provider: 'ByteDance',
    featured: true,
    tags: ['Pro', '10s'],
    description: 'Professional dance and movement videos',
    supportsImageInput: true,
    supportsEndFrame: false,
  },
  'wan2.6': {
    name: 'Wan 2.6',
    provider: 'Wan',
    featured: false,
    tags: ['720p', '10s'],
    description: 'High-resolution video generation',
    supportsImageInput: true,
    supportsEndFrame: true,
  },
  'ltx-video': {
    name: 'LTX Video',
    provider: 'LTX',
    featured: true,
    tags: ['4K', '8s', 'Sound'],
    description: 'Up to 4K resolution with synchronized audio',
    supportsImageInput: true,
    supportsEndFrame: false,
    supportsSoundGeneration: true,
  },
  'luma-ray-2': {
    name: 'Luma Ray 2',
    provider: 'Luma',
    featured: true,
    tags: ['Cinematic', '10s', '4K'],
    description: 'Highly realistic cinematic motion and physics',
    supportsImageInput: true,
    supportsEndFrame: true,
    supportsVideoExtension: true,
    supportsVideoInterpolation: true,
    supportsModifyVideo: true,
  },
  'luma-ray-flash-2': {
    name: 'Luma Ray 2 Flash',
    provider: 'Luma',
    featured: true,
    tags: ['Fast', '15s', '720p'],
    description: 'Ultra-fast video generation with consistent motion',
    supportsImageInput: true,
    supportsEndFrame: true,
    supportsVideoExtension: true,
    supportsVideoInterpolation: true,
    supportsModifyVideo: true,
  },
  'luma-reframe': {
    name: 'Luma Reframe',
    provider: 'Luma',
    featured: true,
    tags: ['Transform', 'Style', 'Motion'],
    description: 'Transform video with motion, style, and cinematic effects',
    supportsImageInput: false,
    supportsEndFrame: false,
    supportsVideoInput: true,
  },
  'topaz-video-upscale': {
    name: 'Topaz Video Upscale',
    provider: 'Topaz Labs',
    featured: true,
    tags: ['Professional', '720p-4k', '60fps'],
    description: 'Professional-grade video upscaling up to 4K resolution and 60fps',
    supportsImageInput: false,
    supportsEndFrame: false,
    supportsVideoInput: true,
  },
} as const;

export type VideoUniversalModelId = keyof typeof VIDEO_UNIVERSAL_MODEL_DEFS;

export const MODELS = Object.keys(VIDEO_UNIVERSAL_MODEL_DEFS) as VideoUniversalModelId[];
