import React, { lazy } from 'react';
import type { NodeTypes } from '@xyflow/react';
import { createDynamicNodeWrapper, getNodeComponent } from '../utils/dynamicNodeImports';
import CyberEdge from '../components/CyberEdge';

const LocalLTXNode = lazy(() => import('../nodes/LocalLTXNode'));

export const initialEdgeTypes = {
  cyber: CyberEdge,
};

export const initialNodeTypes: NodeTypes = {
  inputNode: createDynamicNodeWrapper(getNodeComponent('InputNode')),
  input: createDynamicNodeWrapper(getNodeComponent('InputNode')),
  textNode: createDynamicNodeWrapper(getNodeComponent('TextNode')),
  prompt: createDynamicNodeWrapper(getNodeComponent('TextNode')),
  text: createDynamicNodeWrapper(getNodeComponent('TextNode')),
  imageNode: createDynamicNodeWrapper(getNodeComponent('ImageNode')),
  imageElement: createDynamicNodeWrapper(getNodeComponent('ImageElementNode')),
  assetNode: createDynamicNodeWrapper(getNodeComponent('AssetNode')),
  sourceMediaNode: createDynamicNodeWrapper(getNodeComponent('SourceMediaNode')),
  workflowTemplate: createDynamicNodeWrapper(getNodeComponent('WorkflowNode')),
  imageAnalyzer: createDynamicNodeWrapper(getNodeComponent('ImageAnalyzerNode')),
  generator: createDynamicNodeWrapper(getNodeComponent('GeneratorNode')),
  creativeUpscale: createDynamicNodeWrapper(getNodeComponent('CreativeUpScaleNode')),
  precisionUpscale: createDynamicNodeWrapper(getNodeComponent('PrecisionUpScaleNode')),
  relight: createDynamicNodeWrapper(getNodeComponent('RelightNode')),
  styleTransfer: createDynamicNodeWrapper(getNodeComponent('StyleTransferNode')),
  removeBackground: createDynamicNodeWrapper(getNodeComponent('RemoveBackgroundNode')),
  layerEditor: createDynamicNodeWrapper(getNodeComponent('LayerEditorNode')),
  layerNode: createDynamicNodeWrapper(getNodeComponent('LayerNode')),
  remotionLayer: createDynamicNodeWrapper(getNodeComponent('LayerNode')),
  fluxReimagine: createDynamicNodeWrapper(getNodeComponent('FluxReimagineNode')),
  fluxImageExpand: createDynamicNodeWrapper(getNodeComponent('FluxImageExpandNode')),
  seedreamExpand: createDynamicNodeWrapper(getNodeComponent('SeedreamExpandNode')),
  ideogramExpand: createDynamicNodeWrapper(getNodeComponent('IdeogramExpandNode')),
  skinEnhancer: createDynamicNodeWrapper(getNodeComponent('SkinEnhancerNode')),
  ideogramInpaint: createDynamicNodeWrapper(getNodeComponent('IdeogramInpaintNode')),
  changeCamera: createDynamicNodeWrapper(getNodeComponent('ChangeCameraNode')),
  kling3: createDynamicNodeWrapper(getNodeComponent('Kling3Node')),
  kling3Omni: createDynamicNodeWrapper(getNodeComponent('Kling3OmniNode')),
  kling3Motion: createDynamicNodeWrapper(getNodeComponent('Kling3MotionControlNode')),
  klingElementsPro: createDynamicNodeWrapper(getNodeComponent('KlingElementsProNode')),
  klingO1: createDynamicNodeWrapper(getNodeComponent('KlingO1Node')),
  minimaxLive: createDynamicNodeWrapper(getNodeComponent('MiniMaxLiveNode')),
  wan26: createDynamicNodeWrapper(getNodeComponent('Wan26VideoNode')),
  seedance: createDynamicNodeWrapper(getNodeComponent('SeedanceNode')),
  ltxVideo2Pro: createDynamicNodeWrapper(getNodeComponent('LtxVideo2ProNode')),
  runwayGen45: createDynamicNodeWrapper(getNodeComponent('RunwayGen45Node')),
  runwayGen4Turbo: createDynamicNodeWrapper(getNodeComponent('RunwayGen4TurboNode')),
  runwayActTwo: createDynamicNodeWrapper(getNodeComponent('RunwayActTwoNode')),
  pixVerseV5Transition: createDynamicNodeWrapper(getNodeComponent('PixVerseV5TransitionNode')),
  omniHuman: createDynamicNodeWrapper(getNodeComponent('OmniHumanNode')),
  vfx: createDynamicNodeWrapper(getNodeComponent('VfxNode')),
  creativeVideoUpscale: createDynamicNodeWrapper(getNodeComponent('CreativeVideoUpscaleNode')),
  precisionVideoUpscale: createDynamicNodeWrapper(getNodeComponent('PrecisionVideoUpscaleNode')),
  textToIcon: createDynamicNodeWrapper(getNodeComponent('TextToIconNode')),
  imageToPrompt: createDynamicNodeWrapper(getNodeComponent('ImageToPromptNode')),
  corridorKey: createDynamicNodeWrapper(getNodeComponent('CorridorKeyNode')),
  pixVerseSoundEffect: createDynamicNodeWrapper(getNodeComponent('PixVerseSoundEffectNode')),
  ltxVideo: createDynamicNodeWrapper(getNodeComponent('LtxVideoNode')),
  improvePrompt: createDynamicNodeWrapper(getNodeComponent('ImprovePromptNode')),
  aiImageClassifier: createDynamicNodeWrapper(getNodeComponent('AIImageClassifierNode')),
  strudelNode: createDynamicNodeWrapper(getNodeComponent('StrudelNode')),
  musicGeneration: createDynamicNodeWrapper(getNodeComponent('MusicGenerationNode')),
  soundEffects: createDynamicNodeWrapper(getNodeComponent('SoundEffectsNode')),
  audioIsolation: createDynamicNodeWrapper(getNodeComponent('AudioIsolationNode')),
  voiceover: createDynamicNodeWrapper(getNodeComponent('VoiceoverNode')),
  universalGeneratorAudio: createDynamicNodeWrapper(getNodeComponent('AudioUniversalGeneratorNode')),
  response: createDynamicNodeWrapper(getNodeComponent('ResponseNode')),
  adaptedPrompt: createDynamicNodeWrapper(getNodeComponent('AdaptedPromptNode')),
  comment: createDynamicNodeWrapper(getNodeComponent('CommentNode')),
  routerNode: createDynamicNodeWrapper(getNodeComponent('RouterNode')),
  groupEditing: createDynamicNodeWrapper(getNodeComponent('GroupEditingNode')),
  facialEditing: createDynamicNodeWrapper(getNodeComponent('FacialEditingNode')),
  universalGeneratorImage: createDynamicNodeWrapper(getNodeComponent('ImageUniversalGeneratorNode')),
  universalGeneratorVideo: createDynamicNodeWrapper(getNodeComponent('VideoUniversalGeneratorNode')),
  videoImprove: createDynamicNodeWrapper(getNodeComponent('VideoImproveNode')),
  quiverTextToVector: createDynamicNodeWrapper(getNodeComponent('QuiverTextToVectorGenerationNode')),
  quiverImageToVector: createDynamicNodeWrapper(getNodeComponent('QuiverImageToVectorGenerationNode')),
  tripo3d: createDynamicNodeWrapper(getNodeComponent('Tripo3DNode')),
  textElement: createDynamicNodeWrapper(getNodeComponent('TextElementNode')),
  imageOutput: createDynamicNodeWrapper(getNodeComponent('ImageOutputNode')),
  videoOutput: createDynamicNodeWrapper(getNodeComponent('VideoOutputNode')),
  soundOutput: createDynamicNodeWrapper(getNodeComponent('SoundOutputNode')),
  condition: createDynamicNodeWrapper(getNodeComponent('ConditionNode')),
  iteration: createDynamicNodeWrapper(getNodeComponent('IterationNode')),
  variable: createDynamicNodeWrapper(getNodeComponent('VariableNode')),
  socialPublisher: createDynamicNodeWrapper(getNodeComponent('SocialPublisherNode')),
  cloudSync: createDynamicNodeWrapper(getNodeComponent('CloudSyncNode')),
  simplifiedGenerator: createDynamicNodeWrapper(getNodeComponent('SimplifiedGeneratorNode')),
  textLLM: createDynamicNodeWrapper(getNodeComponent('TextLLMNode')),
  imageSegmentation: createDynamicNodeWrapper(getNodeComponent('ImageSegmentationNode')),
  localLTX: createDynamicNodeWrapper(LocalLTXNode),
} as any;
