import React, { lazy } from 'react';
import type { NodeTypes } from '@xyflow/react';
import { dynamicNodes, createDynamicNodeWrapper } from '../utils/dynamicNodeImports';
import CyberEdge from '../components/CyberEdge';

const LocalLTXNode = lazy(() => import('../nodes/LocalLTXNode'));

export const initialEdgeTypes = {
  cyber: CyberEdge,
};

export const initialNodeTypes: NodeTypes = {
  inputNode: createDynamicNodeWrapper(dynamicNodes.InputNode),
  input: createDynamicNodeWrapper(dynamicNodes.InputNode),
  textNode: createDynamicNodeWrapper(dynamicNodes.TextNode),
  prompt: createDynamicNodeWrapper(dynamicNodes.TextNode),
  text: createDynamicNodeWrapper(dynamicNodes.TextNode),
  imageNode: createDynamicNodeWrapper(dynamicNodes.ImageNode),
  imageElement: createDynamicNodeWrapper(dynamicNodes.ImageElementNode),
  assetNode: createDynamicNodeWrapper(dynamicNodes.AssetNode),
  sourceMediaNode: createDynamicNodeWrapper(dynamicNodes.SourceMediaNode),
  workflowTemplate: createDynamicNodeWrapper(dynamicNodes.WorkflowNode),
  imageAnalyzer: createDynamicNodeWrapper(dynamicNodes.ImageAnalyzerNode),
  generator: createDynamicNodeWrapper(dynamicNodes.GeneratorNode),
  creativeUpscale: createDynamicNodeWrapper(dynamicNodes.CreativeUpScaleNode),
  precisionUpscale: createDynamicNodeWrapper(dynamicNodes.PrecisionUpScaleNode),
  relight: createDynamicNodeWrapper(dynamicNodes.RelightNode),
  styleTransfer: createDynamicNodeWrapper(dynamicNodes.StyleTransferNode),
  removeBackground: createDynamicNodeWrapper(dynamicNodes.RemoveBackgroundNode),
  layerEditor: createDynamicNodeWrapper(dynamicNodes.LayerEditorNode),
  layerNode: createDynamicNodeWrapper(dynamicNodes.LayerNode),
  remotionLayer: createDynamicNodeWrapper(dynamicNodes.LayerNode),
  fluxReimagine: createDynamicNodeWrapper(dynamicNodes.FluxReimagineNode),
  fluxImageExpand: createDynamicNodeWrapper(dynamicNodes.FluxImageExpandNode),
  seedreamExpand: createDynamicNodeWrapper(dynamicNodes.SeedreamExpandNode),
  ideogramExpand: createDynamicNodeWrapper(dynamicNodes.IdeogramExpandNode),
  skinEnhancer: createDynamicNodeWrapper(dynamicNodes.SkinEnhancerNode),
  ideogramInpaint: createDynamicNodeWrapper(dynamicNodes.IdeogramInpaintNode),
  changeCamera: createDynamicNodeWrapper(dynamicNodes.ChangeCameraNode),
  kling3: createDynamicNodeWrapper(dynamicNodes.Kling3Node),
  kling3Omni: createDynamicNodeWrapper(dynamicNodes.Kling3OmniNode),
  kling3Motion: createDynamicNodeWrapper(dynamicNodes.Kling3MotionControlNode),
  klingElementsPro: createDynamicNodeWrapper(dynamicNodes.KlingElementsProNode),
  klingO1: createDynamicNodeWrapper(dynamicNodes.KlingO1Node),
  minimaxLive: createDynamicNodeWrapper(dynamicNodes.MiniMaxLiveNode),
  wan26: createDynamicNodeWrapper(dynamicNodes.Wan26VideoNode),
  seedance: createDynamicNodeWrapper(dynamicNodes.SeedanceNode),
  ltxVideo2Pro: createDynamicNodeWrapper(dynamicNodes.LtxVideo2ProNode),
  runwayGen45: createDynamicNodeWrapper(dynamicNodes.RunwayGen45Node),
  runwayGen4Turbo: createDynamicNodeWrapper(dynamicNodes.RunwayGen4TurboNode),
  runwayActTwo: createDynamicNodeWrapper(dynamicNodes.RunwayActTwoNode),
  pixVerseV5Transition: createDynamicNodeWrapper(dynamicNodes.PixVerseV5TransitionNode),
  omniHuman: createDynamicNodeWrapper(dynamicNodes.OmniHumanNode),
  vfx: createDynamicNodeWrapper(dynamicNodes.VfxNode),
  creativeVideoUpscale: createDynamicNodeWrapper(dynamicNodes.CreativeVideoUpscaleNode),
  precisionVideoUpscale: createDynamicNodeWrapper(dynamicNodes.PrecisionVideoUpscaleNode),
  textToIcon: createDynamicNodeWrapper(dynamicNodes.TextToIconNode),
  imageToPrompt: createDynamicNodeWrapper(dynamicNodes.ImageToPromptNode),
  corridorKey: createDynamicNodeWrapper(dynamicNodes.CorridorKeyNode),
  pixVerseSoundEffect: createDynamicNodeWrapper(dynamicNodes.PixVerseSoundEffectNode),
  ltxVideo: createDynamicNodeWrapper(dynamicNodes.LtxVideoNode),
  improvePrompt: createDynamicNodeWrapper(dynamicNodes.ImprovePromptNode),
  aiImageClassifier: createDynamicNodeWrapper(dynamicNodes.AIImageClassifierNode),
  strudelNode: createDynamicNodeWrapper(dynamicNodes.StrudelNode),
  musicGeneration: createDynamicNodeWrapper(dynamicNodes.MusicGenerationNode),
  soundEffects: createDynamicNodeWrapper(dynamicNodes.SoundEffectsNode),
  audioIsolation: createDynamicNodeWrapper(dynamicNodes.AudioIsolationNode),
  voiceover: createDynamicNodeWrapper(dynamicNodes.VoiceoverNode),
  universalGeneratorAudio: createDynamicNodeWrapper(dynamicNodes.AudioUniversalGeneratorNode),
  response: createDynamicNodeWrapper(dynamicNodes.ResponseNode),
  adaptedPrompt: createDynamicNodeWrapper(dynamicNodes.AdaptedPromptNode),
  comment: createDynamicNodeWrapper(dynamicNodes.CommentNode),
  routerNode: createDynamicNodeWrapper(dynamicNodes.RouterNode),
  groupEditing: createDynamicNodeWrapper(dynamicNodes.GroupEditingNode),
  facialEditing: createDynamicNodeWrapper(dynamicNodes.FacialEditingNode),
  universalGeneratorImage: createDynamicNodeWrapper(dynamicNodes.ImageUniversalGeneratorNode),
  universalGeneratorVideo: createDynamicNodeWrapper(dynamicNodes.VideoUniversalGeneratorNode),
  videoImprove: createDynamicNodeWrapper(dynamicNodes.VideoImproveNode),
  quiverTextToVector: createDynamicNodeWrapper(dynamicNodes.QuiverTextToVectorGenerationNode),
  quiverImageToVector: createDynamicNodeWrapper(dynamicNodes.QuiverImageToVectorGenerationNode),
  tripo3d: createDynamicNodeWrapper(dynamicNodes.Tripo3DNode),
  textElement: createDynamicNodeWrapper(dynamicNodes.TextElementNode),
  imageOutput: createDynamicNodeWrapper(dynamicNodes.ImageOutputNode),
  videoOutput: createDynamicNodeWrapper(dynamicNodes.VideoOutputNode),
  soundOutput: createDynamicNodeWrapper(dynamicNodes.SoundOutputNode),
  condition: createDynamicNodeWrapper(dynamicNodes.ConditionNode),
  iteration: createDynamicNodeWrapper(dynamicNodes.IterationNode),
  variable: createDynamicNodeWrapper(dynamicNodes.VariableNode),
  socialPublisher: createDynamicNodeWrapper(dynamicNodes.SocialPublisherNode),
  cloudSync: createDynamicNodeWrapper(dynamicNodes.CloudSyncNode),
  simplifiedGenerator: createDynamicNodeWrapper(dynamicNodes.SimplifiedGeneratorNode),
  textLLM: createDynamicNodeWrapper(dynamicNodes.TextLLMNode),
  imageSegmentation: createDynamicNodeWrapper(dynamicNodes.ImageSegmentationNode),
  localLTX: createDynamicNodeWrapper(LocalLTXNode),
} as any;
